# Generated by Django 5.0.5 on 2024-05-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image_data1',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_data2',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_data3',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_data4',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='house',
            name='image_data5',
            field=models.ImageField(blank=True, null=True, upload_to='home'),
        ),
        migrations.AlterField(
            model_name='house',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
